// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: dynamic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamicService_Invoke_FullMethodName = "/dynamic.DynamicService/Invoke"
)

// DynamicServiceClient is the client API for DynamicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynamicServiceClient interface {
	Invoke(ctx context.Context, in *GrpcCall, opts ...grpc.CallOption) (*GrpcResult, error)
}

type dynamicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicServiceClient(cc grpc.ClientConnInterface) DynamicServiceClient {
	return &dynamicServiceClient{cc}
}

func (c *dynamicServiceClient) Invoke(ctx context.Context, in *GrpcCall, opts ...grpc.CallOption) (*GrpcResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrpcResult)
	err := c.cc.Invoke(ctx, DynamicService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicServiceServer is the server API for DynamicService service.
// All implementations must embed UnimplementedDynamicServiceServer
// for forward compatibility.
type DynamicServiceServer interface {
	Invoke(context.Context, *GrpcCall) (*GrpcResult, error)
	mustEmbedUnimplementedDynamicServiceServer()
}

// UnimplementedDynamicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamicServiceServer struct{}

func (UnimplementedDynamicServiceServer) Invoke(context.Context, *GrpcCall) (*GrpcResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedDynamicServiceServer) mustEmbedUnimplementedDynamicServiceServer() {}
func (UnimplementedDynamicServiceServer) testEmbeddedByValue()                        {}

// UnsafeDynamicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicServiceServer will
// result in compilation errors.
type UnsafeDynamicServiceServer interface {
	mustEmbedUnimplementedDynamicServiceServer()
}

func RegisterDynamicServiceServer(s grpc.ServiceRegistrar, srv DynamicServiceServer) {
	// If the following call pancis, it indicates UnimplementedDynamicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamicService_ServiceDesc, srv)
}

func _DynamicService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicServiceServer).Invoke(ctx, req.(*GrpcCall))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamicService_ServiceDesc is the grpc.ServiceDesc for DynamicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamic.DynamicService",
	HandlerType: (*DynamicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _DynamicService_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dynamic.proto",
}
