// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: dynamic.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrpcEndpoint  string                 `protobuf:"bytes,1,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	Args          []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcCall) Reset() {
	*x = GrpcCall{}
	mi := &file_dynamic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcCall) ProtoMessage() {}

func (x *GrpcCall) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcCall.ProtoReflect.Descriptor instead.
func (*GrpcCall) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcCall) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *GrpcCall) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type GrpcResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcResult) Reset() {
	*x = GrpcResult{}
	mi := &file_dynamic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcResult) ProtoMessage() {}

func (x *GrpcResult) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcResult.ProtoReflect.Descriptor instead.
func (*GrpcResult) Descriptor() ([]byte, []int) {
	return file_dynamic_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcResult) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GrpcResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_dynamic_proto protoreflect.FileDescriptor

const file_dynamic_proto_rawDesc = "" +
	"\n" +
	"\rdynamic.proto\x12\adynamic\"C\n" +
	"\bGrpcCall\x12#\n" +
	"\rgrpc_endpoint\x18\x01 \x01(\tR\fgrpcEndpoint\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\":\n" +
	"\n" +
	"GrpcResult\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2B\n" +
	"\x0eDynamicService\x120\n" +
	"\x06Invoke\x12\x11.dynamic.GrpcCall\x1a\x13.dynamic.GrpcResultB\x11Z\x0fgrpc-dynamic/pbb\x06proto3"

var (
	file_dynamic_proto_rawDescOnce sync.Once
	file_dynamic_proto_rawDescData []byte
)

func file_dynamic_proto_rawDescGZIP() []byte {
	file_dynamic_proto_rawDescOnce.Do(func() {
		file_dynamic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamic_proto_rawDesc), len(file_dynamic_proto_rawDesc)))
	})
	return file_dynamic_proto_rawDescData
}

var file_dynamic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dynamic_proto_goTypes = []any{
	(*GrpcCall)(nil),   // 0: dynamic.GrpcCall
	(*GrpcResult)(nil), // 1: dynamic.GrpcResult
}
var file_dynamic_proto_depIdxs = []int32{
	0, // 0: dynamic.DynamicService.Invoke:input_type -> dynamic.GrpcCall
	1, // 1: dynamic.DynamicService.Invoke:output_type -> dynamic.GrpcResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dynamic_proto_init() }
func file_dynamic_proto_init() {
	if File_dynamic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamic_proto_rawDesc), len(file_dynamic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamic_proto_goTypes,
		DependencyIndexes: file_dynamic_proto_depIdxs,
		MessageInfos:      file_dynamic_proto_msgTypes,
	}.Build()
	File_dynamic_proto = out.File
	file_dynamic_proto_goTypes = nil
	file_dynamic_proto_depIdxs = nil
}
